# This is a basic workflow to help you get started with Actions

name: Bitmap Split MUX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - feature/*

  pull_request:
    branches:
      - master
      - release/*

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: MSBuild
    runs-on: windows-latest

    strategy:
      matrix:
        config:
          - Debug
          - Release

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Bitmap Split MUX
      run: build-bmp-tools.bat ${{ matrix.config }}
      shell: cmd
