# This is a basic workflow to help you get started with Actions

name: sakura build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: MSBuild
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: check env
      run: set
      shell: cmd

    - uses: franzdiebold@github-env-vars-action@v1.0.0

    - name: Print environment variables
      run: |
        echo "GITHUB_REPOSITORY_OWNER=$GITHUB_REPOSITORY_OWNER"
        echo "GITHUB_REPOSITORY_NAME=$GITHUB_REPOSITORY_NAME"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"
        echo "GITHUB_SHA_SHORT=$GITHUB_SHA_SHORT"
        echo "GITHUB_REF_NAME=$GITHUB_REF_NAME"

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      run: msbuild sakura.sln
      shell: cmd
