# This is a basic workflow to help you get started with Actions

name: sakura build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: MSBuild
    runs-on: windows-latest

    strategy:
      matrix:
        config: ["Debug", "Release"]    
        platform: ["Win32", "x64"]    

    steps:
    - uses: actions/checkout@v1

    - name: check env
      run: set
      shell: cmd

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0
      
    - name: MSBuild
      run: build-sln.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd
      
    - name: zipArtifacts
      run: zipArtifacts.bat ${{ matrix.platform }} ${{ matrix.config }}
      shell: cmd

    - name: Upload
      uses: actions/upload-artifact@v1
      with:
        name: exe ${{ matrix.platform }} ${{ matrix.config }}
        path: './sakura-**.zip'
